version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - TICKETMASTER_API_KEY=${TICKETMASTER_API_KEY}
      - FRONTEND_URI=${FRONTEND_URI}
    ports:
      - "8080:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
      - BACKEND_URI=${BACKEND_URI}
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend

